[package]
name = "defunctionalize"
version = "0.1.0"
authors = ["Cameron Eldridge <cam.eldridge@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
heck = "0.3.1"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
